# repos:
#   - repo: https://github.com/iterative/dvc
#     rev: 2.9.5
#     hooks:
#       - id: dvc-pre-commit
#         language_version: python3
#         stages:
#           - commit
#       - id: dvc-pre-push
#         additional_dependencies: [".[s3]"]
#         language_version: python3
#         stages:
#           - push
#       - always_run: true
#         id: dvc-post-checkout
#         language_version: python3
#         stages:
#           - post-checkout

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      # - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args: ["--py39-plus"]

  - repo: https://github.com/PyCQA/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: [
        --recursive,
        --in-place,
        --remove-all-unused-imports,
        --remove-unused-variables
        ]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile=black"]

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.3.1
    hooks:
      - id: nbqa-pyupgrade
        args: ["--py39-plus"]
      - id: nbqa-isort
        args: ["--profile=black"]
      - id: nbqa-black
