repos:
-   repo: https://github.com/iterative/dvc
    rev: main
    hooks:
      - id: dvc-pre-commit
        language_version: python3
        stages:
          - commit
      - id: dvc-pre-push
        additional_dependencies: ['.[s3]']
        language_version: python3
        stages:
          - push
      - always_run: true
        id: dvc-post-checkout
        language_version: python3
        stages:
          - post-checkout

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: check-ast
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending
      - id: detect-aws-credentials
      - id: detect-private-key

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
      - args: [--py38-plus]

  - repo: https://github.com/PyCQA/autoflake
    rev: latest
    hooks:
      - id: autoflake
      - args: [
        --recursive,
        --in-place,
        --remove-all-unused-imports,
        --remove-unused-variables
        ]

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile black]

  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black-jupyter
        language_version: python3.8

      # - id: mypy
      #   name: mypy
      #   entry: poetry run mypy .
      #   require_serial: true
      #   language: system
      #   types: [python]
      #   pass_filenames: false
      # - id: flake8
      #   name: flake8
      #   entry: poetry run flake8
      #   language: system
      #   types: [python]