name: pre-commit

on:
  pull_request:
  push:
    branches: [main, master]

env:
  SKIP: dvc-pre-commit, dvc-pre-push

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
